### ISSUE TITLE
Supprimer la limitation d'inscription à des groupes de citoyens

### ISSUE THREAD

**Issue by Luljaze** [m6r/nouslepeuple#12]
Pour le moment on ne peut pas s'inscrire à plus de 10 groupes, le bouton "rejoindre ce groupe" disparaît quand on est déjà inscrit à 10 groupes.
Vérifié.

**Comment by kzwix** [comment]
Je confirme également, ce problème m'a fortement ennuyé.

Pour l'instant, c'est pas catastrophique, vu qu'on n'est pas prévenu des modifications dans les groupes, mais c'est gênant.

Et si on implémente un système d'alertes lié aux nouvelles publications, ça va devenir totalement indispensable.

**Comment by guillaumerobin** [comment]
Corrigé.
