### ISSUE TITLE
Le bouton "ajouter aux favoris" ne fonctionne pas

### ISSUE THREAD

**Issue by Luljaze** [m6r/nouslepeuple#14]
Ni en cliquant directement à partir de l'en-tête dans la liste des articles, ni en cliquant à partir de l'article lui-même : rien ne se passe apparemment, l'article n'est pas ajouté à la catégorie "favoris" du profil. confirmé par 9 personnes.

**Comment by Luljaze** [comment]
8 personnes confirment avoir le même problème

**Comment by lo--ol** [comment]
il suffit de remplacer
$(".favorite").live("click", function .
par
$(document).on('click', '.favorite', function
"live" n'est plus une fonction valide depuis la version 1.9 de jquery (vous utilisez la version 1.11.2)
