### ISSUE TITLE
Modifier le renvoi quand on clique sur un lien vers un article

### ISSUE THREAD

**Issue by Luljaze** [m6r/nouslepeuple#16]
Actuellement, quand on clique sur un lien qui renvoie à un article de NLP, c'est le bas de page qui s'affiche, donc la fin des commentaires. Il serait judicieux que le renvoi se fasse vers le haut de la page pour que l'on puisse lire d'abord l'article, puis les commentaires.

**Comment by guillaumerobin** [comment]
Corrigé dans livraison de lundi =)
