### ISSUE TITLE
Modifier le renvoi quand on clique sur une catégorie de discussion

### ISSUE THREAD

**Issue by Luljaze** [m6r/nouslepeuple#17]
Changer le tri automatique des articles dans les catégories : à l'heure actuelle, quand on clique sur une catégorie à partir de la page d'accueil, on tombe sur « le plus de votes (sous entendu dans les 24 heures)/la catégorie », alors qu'on s'attend à avoir tous les articles de la catégorie, et il faut cliquer sur « tous les articles » puis recliquer sur la catégorie pour obtenir tous les articles de la catégorie (je sais pas si mon explication est claire). Ce qui n'est pas logique puisque dans ce cas, les articles sont triés par ordre chronologique, donc les derniers articles postés sont quand même mis en avant, rendant inutile ce long détour (que peu de gens font, je pense), ce qui explique sans doute en partie la prolifération des articles sur un même thème.

Il faudrait faire en sorte que quand on clique sur une catégorie dans le menu on arrive directement sur « tous les articles / la catégorie »

**Comment by loic-T** [comment]
Point intégré au ticket #20
