### ISSUE TITLE
ajout tags ou hashtags

### ISSUE THREAD

**Issue by naldir** [m6r/nouslepeuple#24]
ajout de tags ou hashtags pour simplifier la recherche et la classification des sujets

**Comment by Luljaze** [comment]
ça existe déjà !!!

**Comment by guillaumerobin** [comment]
Merci de ne pas utiliser Github pour proposer de nouvelles fonctionnalités ou discuter de l'évolution de la plateforme. Utilisez plutôt la catégorie dédiée sur Nous le Peuple.
