### ISSUE TITLE
Stockage des mots de passe

### ISSUE THREAD

**Issue by hferee** [m6r/nouslepeuple#38]
Les mots de passe sont stockés en clair, et pire ils sont envoyés en clair par email.
Il faut les saler/hasher comme il se doit.

**Comment by guillaumerobin** [comment]
Les mots de passe ne sont pas stockés en clair, ni envoyés par mail. Où avez vous vu ça ?

**Comment by hferee** [comment]
J'ai reçu l'email suivant : 

«Votre mot de passe pour Nous le Peuple a récemment été modifié. Veuillez vous connecter en utilisant les éléments ci-dessous, puis changez votre mot de passe depuis votre profil citoyen.

Nom de citoyen: monlogin
Mot de passe: monmotdepasse»

**Comment by hferee** [comment]
J'ajouterai que le lien (sur "vous connecter") ne pointe pas directement sur le site, mais sur un site de tracking «http://mandrillapp.com/track/...» qui semble une très mauvaise idée d'un point de vue de vie privée.
Je précise que l'email provenait de «contact@m6r.fr»

**Comment by guillaumerobin** [comment]
On peut voir ça par mail dev@m6r.fr ?

**Comment by guillaumerobin** [comment]
Les mots de passe ne sont pas stockés en clair, il était envoyé par mail avant d'être stocké en base, c'est supprimé.

**Comment by hferee** [comment]
Ok, je suis rassuré.
Pour info c'était dans recover.php, et on trouve la ligne dans languages/lang_french.conf, ligne 165.

Et qu'en est-il de l'usage de mandrillapp, société de droit américain, qui ne protège donc pas du tout les données personnelles ?
