### ISSUE TITLE
impossibilité d'écrire une apostrophe dans la description du profil sur NLP

### ISSUE THREAD

**Issue by Luljaze** [m6r/nouslepeuple#39]
Dans la partie "présentation" du profil des utilisateurs sur Nous le peuple, l'apostrophe écrite se transforme en  "///" lors de l'enregistrement.
Vérifié.

**Comment by gygde** [comment]
Suggestion: 
Ligne 456 de profile.php, appel de la fonction sanitize(): 
- changer la valeur du paramètre $santype en "4", qui déclenche stripslashes(), au lieu de "3" qui appelle addslashes().

**Comment by ghost** [comment]
Corrigé.
