### ISSUE TITLE
Lien "Contact" Bas De Page Adresse Typo

### ISSUE THREAD

**Issue by Olvarel** [m6r/nouslepeuple#42]
Bonjour,

Le lien "contact" en bas de la page d'accueil dirige l'utilisateur vers une page avec un typo:

https://www.m6r.fr/contat/

Il manque le "c" de contact, et cela dirige vers une "Page Not Found".

Merci de corriger cette petite erreur.

**Comment by ghost** [comment]
Corrigé, merci !

Par contre pas enregistré au bon endroit. Les éléments du site principal ça va sur https://github.com/m6r/wp-themev2 ;)
